project:
  type: website
  output-dir: docs

website:
  title: "Economics PhD Reading Group"
  navbar:
    left:
      - href: index.qmd
        text: Schedule
      - href: sessions.qmd
        text: Sessions

format:
  html:
    theme: litera
    css: styles.css
    toc: false



